<?php
    $this->template('header');
?>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    欢迎进入葡萄微信游戏后台管理
                </h1>
                <small>

                </small>
            </div>
        </div>
    </div>
</div>
<?php
    $this->template('footer');
?>
