<?php
$this->template('header');
?>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>微信公众号列表</h5>
                </div>
                <div class="ibox-content" id="wxChatList">
                    <span ><a class="btn btn-info" name="createWxChat">添加微信公众号</a></span>
                    <div style="padding-top: 30px">
                        <table  style="font-size:12px" align="center" class="table table-hover">
                            <tbody>
                            <tr>
                                <th style="text-align: center;">编号ID</th>
                                <th style="text-align: center">微信公众号名称</th>
                                <th style="text-align: center">appid</th>
                                <th style="text-align: center">appSecret</th>
                                <th style="text-align: center">哈希值</th>
                                <th style="text-align: center">类型</th>
                                <th style="text-align: center">授权类型</th>
                                <th style="text-align: center">操作 </th>
                            </tr>
                            <?php
                            if(!empty( $this->list )){
                                foreach ($this->list as $key => $value){ ?>
                                <tr>
                                    <td style="text-align: center;vertical-align: middle"><?= $key + 1;?></td>
                                    <td style="text-align: center;vertical-align: middle"><?= $value->name?></td>
                                    <td style="text-align: center;vertical-align: middle"><?= $value->appId;?></td>
                                    <td style="text-align: center;vertical-align: middle"><?= $value->appSecret;?></td>
                                    <td style="text-align: center;vertical-align: middle"><?= $value->hash;?>
                                    <td style="text-align: center;vertical-align: middle">
                                        <?php if( $value->type == '1'){
                                            echo '服务号';
                                        }else{
                                            echo '公众号';
                                        }?>
                                    </td>
                                    <td style="text-align: center;vertical-align: middle">
                                        <?php if( $value->authorization == '1'){
                                            echo '静默授权';
                                        }else{
                                            echo 'web授权';
                                        }?>
                                    </td>
                                    <td style="text-align: center;vertical-align: middle">
                                        <button name="editWxChat" class="btn btn-info">修改</button>
                                        <input type="hidden" value="<?= $value->wx_account_id?>" name="wx_account_id">
                                        <input type="hidden" value="<?= $value->appId?>" name="appId">
                                        <input type="hidden" value="<?= $value->name?>" name="name">
                                        <input type="hidden" value="<?= $value->appSecret?>" name="appSecret">
                                        <input type="hidden" value="<?= $value->type?>" name="type">
                                        <input type="hidden" value="<?= $value->authorization?>" name="authorization">
                                    </td>
                                </tr>
                            <?php } }?>
                            </tbody>
                        </table>
                        <?php
                        if(!empty( $this->list )){
                            echo $this->paginateView;
                        }else{
                            echo '<div class="text-center">无数据</div>';
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" name="wxChatAdd" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" id="submitAdd">
        <div class="modal-dialog" role="document" style="width: 700px;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">添加公众号</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group" style="overflow: auto;">
                        <label class="col-sm-2 label-12" style="padding-top: 4px">名称</label>
                        <div class="col-sm-10" style="width:70%;">
                            <input type="text" name="name">
                        </div>
                    </div>
                    <div class="form-group" style="overflow: auto;">
                        <label class="col-sm-2 label-12" style="padding-top: 5px">appid</label>
                        <div class="col-sm-10" style="width:70%;">
                            <input type="text" name="appid">
                        </div>
                    </div>
                    <div class="form-group" style="overflow: auto;">
                        <label class="col-sm-2 label-12" style="padding-top: 5px">appSecret</label>
                        <div class="col-sm-10" style="width:70%;">
                            <input type="text" name="appSecret">
                        </div>
                    </div>
                    <div class="form-group" style="overflow: auto;">
                        <label class="col-sm-2 label-12" style="padding-top: 5px">类型</label>
                        <div class="col-sm-10" style="width:70%;">
                            <select class="form-control" name="type">
                                <option value="">请选择</option>
                                    <option value="1">服务号</option>
                                    <option value="2">公众号</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group" style="overflow: auto;">
                        <label class="col-sm-2 label-12" style="padding-top: 5px">授权类型</label>
                        <div class="col-sm-10" style="width:70%;">
                            <select class="form-control" name="authorization">
                                <option value="">请选择</option>
                                <option value="1">静默授权</option>
                                <option value="2">web授权</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary" name="submit">提交</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" name="wxChatEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" id="submitEdit">
        <div class="modal-dialog" role="document" style="width: 700px;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">修改公众号</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group" style="overflow: auto;">
                        <label class="col-sm-2 label-12" style="padding-top: 4px">名称</label>
                        <div class="col-sm-10" style="width:70%;">
                            <input type="text" name="name">
                            <input type="hidden" name="wx_account_id">
                        </div>
                    </div>
                    <div class="form-group" style="overflow: auto;">
                        <label class="col-sm-2 label-12" style="padding-top: 5px">appid</label>
                        <div class="col-sm-10" style="width:70%;">
                            <input type="text" name="appid">
                        </div>
                    </div>
                    <div class="form-group" style="overflow: auto;">
                        <label class="col-sm-2 label-12" style="padding-top: 5px">appSecret</label>
                        <div class="col-sm-10" style="width:70%;">
                            <input type="text" name="appSecret">
                        </div>
                    </div>
                    <div class="form-group" style="overflow: auto;">
                        <label class="col-sm-2 label-12" style="padding-top: 5px">类型</label>
                        <div class="col-sm-10" style="width:70%;">
                            <select class="form-control" name="type">
                            </select>
                        </div>
                    </div>
                    <div class="form-group" style="overflow: auto;">
                        <label class="col-sm-2 label-12" style="padding-top: 5px">授权类型</label>
                        <div class="col-sm-10" style="width:70%;">
                            <select class="form-control" name="authorization">
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="button" class="btn btn-primary" name="submit">提交</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/js/wxgame/WxChatListList.js">
</script>
<script type="text/javascript">

    $(document).ready(function(){
        var wxChatList = new WxChatListList('#wxChatList', '#submitAdd', '#submitEdit');
    });

</script>

<?php
$this->template('modal');
?>
<?php
$this->template('footer');
?>
