<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>微信公众号后台</title>
    <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon"/>
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/fonts/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">

    <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon"/>
    <link href="/css/_.css" rel="stylesheet">
    <link href="/css/dropzone-4.3.0/basic.css" rel="stylesheet">
    <link href="/css/dropzone-4.3.0/dropzone.css" rel="stylesheet">

    <script src="/js/jquery-2.1.1.js"></script>
    <script src="/js/bootstrap.js"></script>
    <script src="/js/plugins/validate/jquery.validate.min.js"></script>
    <script src="/js/plugins/layer/laydate/laydate.js"></script>

    <!-- <script src="/js/dropzone-4.3.0/dropzone-amd-module.js"></script> -->
    <script src="/js/dropzone-4.3.0/dropzone.js"></script>
    <script type="text/javascript">
        $(function(){
            $(".nav").find('li.active').parent().parent('li').addClass('active');
        })
    </script>
</head>
<body>
<div id="wrapper">
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element" style="overflow:auto;">
						<span style="float:left; margin-right: 10px;">
							<img src="/images/user.png" class="img-circle" alt="image" style="width: 50px; height: 50px; float: left;">
						</span>
	                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
	                        <span class="clear">
	                        	<span class="block m-t-xs">
	                        		<strong class="font-bold"></strong>
								</span>
								<span class="text-muted text-xs block">　Admin</span><br>
                                <span class="text-muted text-xs block">　微信公众号后台管理员</span>
							</span>
						</a>
                    </div>
                    <div class="logo-element">
                        WxGame
                    </div>
                </li>
               <li class="">
                    <a href="/"><i class="fa fa-th-large"></i> <span class="nav-label">首页</span></a>
               </li>
               <li class="">
                    <a href=""><i class="fa fa-th-large"></i> <span class="nav-label">微信公众号</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse" aria-expanded="false" style="height: 0px;">
                        <li class="<?php if($this->type == 'wechatlist'){echo 'active';}?>">
                            <a href="/wechat/list">公众号列表</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    <form role="search" class="navbar-form-custom" method="post" action="search_results.html">
                        <div class="form-group">
<!--                            <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">-->
                        </div>
                    </form>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="/logout">
                            <i class="fa fa-sign-out"></i> Log out
                        </a>
                    </li>
                </ul>
            </nav>
        </div>