<div class="modal fade" id="dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body" name="content">
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    showmodal = function(text)
    {
        $('[name=content]', '#dialog').text(text);
        $('#dialog').modal('show');
    }
</script>