<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>葡萄微信接口平台 | Login</title>
    <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon"/>
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/fonts/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
</head>
<body class="gray-bg">
    <div class="middle-box text-center loginscreen  animated fadeInDown" id="signin">
        <div>
            <div>
                <h1 class="logo-name"></h1>
            </div>
            <h3>葡萄微信接口平台</h3>
                <div class="form-group">
                    <input type="email" name="username" class="form-control" placeholder="Username" required="">
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="Password" required="">
                </div>
                <buttontton name="submit" class="btn btn-primary block full-width m-b">Login</buttontton>
        </div>
    </div>
    <script src="/js/jquery-2.1.1.js"></script>
    <script src="/js/wxgame/signin.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
                var signin = new Signin('#signin');
        });
    </script>
</body>

</html>
