<?php
$signPackage = $this->signPackage;

//var_dump($signPackage);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="user-scalable=no"/>
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <title>老爸、萌娃并肩大战“麦斯丝”，赢《海底总动员2》电影票！</title>
    <style>
        html,body{
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #212253;
        }
        #tipPage{
            z-index: 999;
            position: absolute;
            left: 0;
            bottom: 0;
            top: 0;
            right: 0;
            background-color: #0a0b2c;
            display: none;
        }
        #tipPage h2{
            color: #fff;
            text-align: center;
            font-size: 36px;
            position: absolute;
            top: 50%;
            margin-top: -24px;
            left: 0;
            width: 100%;
        }
        .container{
            white-space: nowrap;
            background-size: cover;
            background-position: 50% 50%;
        }
        #qrbox{
            position: absolute;
            bottom: 12px;
            left: 0;
            width: 100%;
            text-align: center;
            display: none;
            z-index: 99;
        }
        #qrbox img{
            width: 35%;
        }
    </style>
</head>
<body>
    <section class="container" id="tipPage">
        <h2>请将手机竖起,以便更好的体验</h2>
    </section>
    <canvas id="gameCanvas" width="100%" height="100%"></canvas>
    <div id="qrbox">
        <img src="/images/res/qr.png">
    </div>
</body>
</html>
<script src="/js/src/inet.min.js"></script>
<!--<script src="src/cp.min.js"></script>-->
<script src="/js/main.js"></script>
<script>
    function hengshuping(){
        if(window.orientation==180||window.orientation==0){
            document.getElementById('tipPage').style.display = 'none';
        };
        if(window.orientation==90||window.orientation==-90){
            document.getElementById('tipPage').style.display = 'block';
        };
    }
    window.addEventListener("onorientationchange" in window ? "orientationchange" : "resize", hengshuping, false);
</script>

<script type="text/javascript" src="//res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>

<script type="text/javascript">

    window.wxData = {
        "appId": "",
//        "imgUrl": "http://ldev.wxgame.putao.com/images/maisisi.png",
        "imgUrl": "http://naoliwang.kemido.com/images/maisisi.jpg",
        "link" : location.href,
        "desc": "我刚发现了一款好游戏，你要不要也来试试？",
        "title": '老爸、萌娃并肩大战“麦斯丝”，赢《海底总动员2》电影票！'
    };
    window.config = {
        "appId": '<?php echo $signPackage["appId"];?>',
        "timestamp": '<?php echo $signPackage["timestamp"];?>',
        "nonceStr": '<?php echo $signPackage["nonceStr"];?>',
        "signature": '<?php echo $signPackage["signature"];?>'
    };
</script>
<script type="text/javascript" src="/js/wx.js"></script>
<script>
    var _hmt = _hmt || [];
    (function() {
        var hm = document.createElement("script");
        hm.src = "//hm.baidu.com/hm.js?a1d9dafdc1053f0fae7d8ae2157ecd26";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>